### ISSUE TITLE
feedback from Alison Hill

### ISSUE THREAD

**Issue by gvwilson** [lexnederbragt/ten_quick_tips_live_coding#5]
From @apreshill:

1. Consider changing title to "Ten Quick Tips For Using Participatory Live Coding to Teach" (for some reason, I find the current title took me a few times to parse- I don't claim this is better, it may actually be more awkward, but having the 3 -ing verbs together made me trip over the title)

2. Sentence 1: perhaps make it more clear what "live programming" is. Maybe: "Participatory live coding is a technique where a teacher or instructor writes and narrates code out loud as they teach, and invites learners to join them by writing and executing the same code. Learners watch as an instructor writes code live in real time, typically via one or more projector screens that show the same screen as the instructor sees. Instructors also read as they type out loud, explaining the different elements and principles that are relevant for learners to understand the code. At the same time, each learner is invited to copy and execute the exact code or commands that are being written on their own work station. Learners thus ‘code-along’ with the instructor. There are frequent, often short, exercises, where learners are asked to solve a small relevant problem on their own." 
  - Is that a fair way to rephrase? I feel like the current definition is a bit circular, like live coding -> live programming, and the watching plus doing elements seemed muddy.

3. I see a few instances of "Live coding" and "live-coding" (see pg 2 for example). Try to be consistent with what the term is.

4. Tip 1: I feel like the phrase "I do, we do, you do" encompasses the spirit of para 1 here- worthwhile to include as a useful mnemonic?

5. Tip 3: typo: "Your will tire your voice less"

6. Tip 5: rephrase "Avoid distractions"?

7. Tip 6: or even better, have *learners* draw or fill in diagrams themselves? Thinking about how we made handouts for the tidymodels workshop that were fill-in-the-blank diagrams- a lot of people gave me feedback that those were surprisingly useful and also something they could physically take home. I think it is one of the "cons" for this kind of live coding - learners may feel distracted by having to furiously copy things down that they fear to be ephemeral but that they want to remember.

8. Tip 7: worth saying, you need to practice? Basically, don't assume less prep because of the live component- it can actually be harder to deliver and certainly can make you feel more vulnerable as an instructor. Like, would be nice to start with a well-developed and tested lesson as recommended here, but what if that is not an option? My friend Jackie always says "Don't practice until you get it right, practice until you can't get it wrong." :)

9. Conclusion: typos "then when presenting slides" --> "than" /  "this in an instance"--> "in an instant"

**Comment by raynamharris** [comment]
perhaps "Ten Quick Tips For Teaching Using/With Participatory Live Coding"?

**Comment by lexnederbragt** [comment]
Thanks, @apreshill! Very useful feedback. These are addressed in the [latest commit](448663e). Also thanks to @raynamharris for the title suggestion.

1. Thanks both, I've chosen "Ten Quick Tips For Teaching With Participatory Live Coding"

2. Great explanation! I've used it as suggested

3. fixed, thanks

4. I am going to ask @gvwilson to address this one

5. Fixed

6. Thanks, good idea!

7. I've added a sentence about having learners do this themselves

8. I've added a sentence about practicing

9. Fixed
