### ISSUE TITLE
feedback from Rayna Harris

### ISSUE THREAD

**Issue by raynamharris** [lexnederbragt/ten_quick_tips_live_coding#6]
- Who uses it: can you cite the Instructor training curriculum? This is the latest citation. I'm not certain it has the "participatory" language, but it might. 

- Tips 1-5 and 9: All of these paragraphs begin with what the instructor should do without first providing context for why this tip is important. For instance, tip 1 could start with something like "When using participatory live coding, you must teach and program at a pace that allows learners to follow along and not get left behind. To do this, you will need to go slower than if you were coding alone. Say out loud what you are doing..." For the most part, this rationale is in the text, so a little rearrange may do the trick of emphasizing what each tip helps the instructor accomplish. 

- Tip 1: The "Do not copy-paste code" comment will likely elicit some strong reactions. Importantly, you aren't offering an immediate alternative. Maybe you can provide a bridge for people how are using this technique to transition. Something like "If your current practice involves copy-paste, try transitioning to a technique where you, the instructor, type everything in the console, while still allowing  the students to copy and paste text from the resources provided."

- Tip 3: I would add a paragraph about how this is true for remote teaching as well. It is much better when a remote instructor is teaching while standing and looking directly into the camera rather than seated and looking down into the camera. 

- Tip 8: I would flip these sentences. Start with "Experiencing the instructor making a mistake" through positive error framing then go into "no matter how well prepared". Also, elaborate on how to embrace those mistakes by providing a few examples like "read out the error message and explain how it told you what mistake you made" or provide guidance on how to involve the students in the problem-solving. 

- Tip 10: I think there is an opportunity to mention that this is a tip for managing diverse classrooms where you have a range of experience and expertise. 

- Finally, I think it needs a figure. I have one in mind. Let me work on it and send you a draft.

**Comment by raynamharris** [comment]
maybe something like this for a figure

![Screen Shot 2020-03-23 at 11 35 08 AM](https://user-images.githubusercontent.com/7544197/77351054-8491e880-6cfa-11ea-9448-9e6de859b58e.png)

**Comment by lexnederbragt** [comment]
Thanks, @raynamharris! 

- I love the diagram! Could you update the title, and perhaps also the text at the top to the new definition provided by Allison Hill: "Participatory live coding is a technique where a teacher or instructor writes and narrates code out loud as they teach, and invites learners to join them by writing and executing the same code." (see latest version)

> Who uses it 

Good suggestion! The June 2019 Zenodo reference is the most recent and uses the word 'participatory'. I've added a sentence referring to it.

>Tips 1-5 and 9: All of these paragraphs begin with what the instructor should do without first providing context

Good suggestion. As you said, it was not too difficult to adjust the beginning of the tips you listed and now each one flows better.

> Tip 1

Implemented.

> Tip 3

My immediate response is that teaching Participatory Live Coding online is going to require its own ten quick tips...

> Tip 8

I changed the order of the sentences a bit, not fully as you suggested to keep a better flow. I also expanded as per your suggestion.

> Tip 10

Added!

**Comment by raynamharris** [comment]
All the recent edits really help improve the flow of the narrative. 

How's this?

![tipsforteaching-01](https://user-images.githubusercontent.com/7544197/77814858-3110f900-7072-11ea-8692-887c8e8b7f33.png)

**Comment by lexnederbragt** [comment]
Nice! I just realised I forgot to alert you to the fact that the title of tip 5 has changed to "Avoid distractions".

**Comment by lexnederbragt** [comment]
Resolved over email
